Repository contao-bootstrap/grid, pull requests merged in 2019-04, with the labels that each got.

#26 Unterstützung für Größensuffixe bei Alignments
  src/Definition/Column.php
Labels: enhancement

#27 Feature/response tagger
  .travis.yml
  CHANGELOG.md
  composer.json
  src/Component/ContentElement/AbstractGridElement.php
  src/Component/ContentElement/GalleryElement.php
  src/Component/ContentElement/GalleryFactory.php
  src/Component/ContentElement/GridElementFactory.php
  src/Component/ContentElement/GridSeparatorElement.php
  src/Component/ContentElement/GridStartElement.php
  src/Component/ContentElement/GridStopElement.php
  src/Component/FormField/AbstractFormField.php
  src/Component/FormField/AbstractRelatedFormField.php
  src/Component/FormField/GridStartFormField.php
  src/Component/Module/GridModule.php
  src/Component/Module/GridModuleFactory.php
  src/Resources/config/services.yml
Labels: in progress

#28 Support auto grid size
  composer.json
  src/Definition/Column.php
  src/GridBuilder.php
  src/Listener/Dca/GridListener.php
  src/Migration/MigrateAutoGridWidths.php
  src/Resources/config/services.yml
  src/Resources/contao/config/runonce.php
Labels: enhancement, in progress

#29 Implement advanced resets (See #12).
  src/Definition/Column.php
  src/GridBuilder.php
  src/Resources/contao/dca/tl_bs_grid.php
  src/Resources/contao/languages/en/tl_bs_grid.php
Labels: enhancement, in progress
